# permalinks
permalink: pretty
description: "WIRED is the faculty-official IT club for Monash Clayton students. It's open to all studying IT or those who are a little interested."
timezone: "+1000"
gems:
  - jekyll-redirect-from
